{
 "title": "Envoy metrics",
 "time": { "from": "2021-05-02T07:25:36.132Z", "to": "2021-05-02T14:18:19.576Z" },
 "panels": [
  {
   "title": "Request throughput by latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[5m]) - on() rate(envoy_cluster_upstream_rq_time_bucket{le=\"10\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[5m]))",
     "legendFormat": "> 10ms"
    },
    {
     "expr": "(rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[5m]) - on() rate(envoy_cluster_upstream_rq_time_bucket{le=\"100\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[5m]))",
     "legendFormat": "> 100ms"
    },
    {
     "expr": "(rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[5m]) - on() rate(envoy_cluster_upstream_rq_time_bucket{le=\"1000\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[5m]))",
     "legendFormat": "> 1000ms"
    },
    {
     "expr": "(rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[5m]) - on() rate(envoy_cluster_upstream_rq_time_bucket{le=\"5000\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[5m]))",
     "legendFormat": "> 5000ms"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "graph",
   "description": "Total number of transactions by return code",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_internal_upstream_rq_xx{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[2m])",
     "legendFormat": "Rate {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Percent of request > 10 ms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[2m]) - on() rate(envoy_cluster_upstream_rq_time_bucket{le=\"10\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[2m]))/ on() rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[2m]) *100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_internal_upstream_rq_time_count{kubernetes_namespace=\"observability\",envoy_cluster_name=\"ingress_service\"}[2m])",
     "legendFormat": "Request per second"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_time_bucket{le=\"10\",envoy_cluster_name=\"ingress_service\",kubernetes_namespace=\"observability\"}[2m])",
     "legendFormat": "Request / s < 10ms"
    }
   ]
  }
 ]
}